[ACM-22629] - Update observability_enable.adoc to correct indentation of secret
Update observability_enable.adoc to correct indentation of secret:
With the secret yaml file mentioned in step 7. Attach the policies to the role of section https://docs.redhat.com/en/documentation/red_hat_advanced_cluster_management_for_kubernetes/2.13/html-single/observability/index#generate-access-keys we were getting:

error: error parsing thanos.yaml: error converting YAML to JSON: yaml: line 8: did not find expected key
After correcting the indentation the error has been resolved. Please add these changes in 2.12 , 2.14 and further.

BUG : https://issues.redhat.com/browse/ACM-22629